name: ShanShan
version: 2

libraries:
- name: "django"
  version: "1.4"

#wrong

#- name: "qiniu"
#  version: "6.1.8"

handlers:
- url: /static/
  static_path: static

- url: /media/
  static_path: media
